#!/bin/sh
cd ~/rhp/compilation
TMP_FILE=`mktemp -p .`

if [ $# -eq 0 ];
then
    cat help.txt
    exit 0
fi

while getopts ":lho:vt:" opt; do
    case $opt in
        l)
            TMP=0
            ;;
        h)
            cat help.txt
            exit
            ;;
        o)
            OUT_FILE=$OPTARG
            ;;
        v)
            VERBOSE=1
            ;;
        t)
            TMP_FILE=$OPTARG
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit 1
            ;;
        :)
            echo "Option -$OPTARG requires an argument." >&2
            exit 1
            ;;
    esac
done
cd -

shift $(($OPTIND -1))

if [ $VERBOSE ];
then
    echo "Starting Compilation"
    echo "Parsing input"
fi
parse.pl $1 > $TMP_FILE || ( rm $TMP_FILE && exit 0 )

if [ $VERBOSE ];
then
    echo "Compiling rust"
fi

if [ $OUT_FILE ];
then
    echo $OUT_FILE
    rustc -v $TMP_FILE -o $OUT_FILE
else
    rustc -v $TMP_FILE
fi
if [ $TMP ];
then
    rm $TMP_FILE
fi
